---
id: Translation
name: Translation
full: Translation library
description: A translation wrappers library.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Translation
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 3.0.0
  api: 3.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^8.1
  optional:
    ext:
      gettext: '*'
vendor: horde
keywords:
  - gettext
  - icu
  - messageformat
  - json
ci-platform:
  '8.1': not resolvable
  '8.2': not resolvable
  '8.3': not resolvable
  '8.4': not resolvable
  '8.5': not resolvable
  '8.6': not resolvable
ci-platform-flags:
  needs_installer_plugin: false
